# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbaJKNct_8Ill4_NH2WVOA0m_9Qi1ZMq
"""

!pip install ultralytics opencv-python

try:
    import ultralytics
    import cv2
    print("✅ Mubarak ho! Sab set hai. Install ho chuka hai.")
except ImportError:
    print("❌ Abhi install nahi hua. Dubara koshish karni padegi.")

from ultralytics import YOLO
import cv2
from IPython.display import display, Image, clear_output
import io
import time # To control frame rate

# 1. AI Model Load kar rahe hain (Ye 'Nano' model hai, bohot tez hai)
# Pehli baar run karne par ye internet se download hoga.
model = YOLO('yolov8n.pt')

# 2. Webcam on kar rahe hain (0 ka matlab laptop ka camera)
# Note: In Colab, direct access to a physical webcam (cv2.VideoCapture(0))
# might require specific Colab utilities or user permissions setup.
# If this fails, consider uploading a video file or using `google.colab.patches.cv2_imshow`
# for webcam streaming if available.
cap = cv2.VideoCapture(0)

print("Camera starting... (Displaying frames in Colab output).")
print("Press 'Stop' button in Colab or interrupt kernel to stop.")

# Limit the number of frames to process for demonstration in Colab
# Adjust this value or remove if you handle loop termination differently.
max_frames = 100
frame_count = 0

try:
    while frame_count < max_frames:
        # Frame read karna
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame or camera not accessible. Exiting.")
            break

        # 3. AI se detection karwana
        results = model(frame)

        # Detection boxes banana (Plotting)
        annotated_frame = results[0].plot()

        # 4. Colab output par dikhana
        # Convert the frame to JPEG format for display in Colab output
        is_success, buffer = cv2.imencode(".jpg", annotated_frame)
        if is_success:
            i = Image(data=buffer.tobytes())
            clear_output(wait=True) # Clear previous frame for updated display
            display(i)

        # Small delay to control refresh rate and allow output to update
        time.sleep(0.1)
        frame_count += 1

except KeyboardInterrupt:
    print("Process interrupted by user.")

finally:
    # Safayi (Cleanup)
    cap.release()
    print("Camera released and cleanup complete.")
    # cv2.destroyAllWindows() is not needed and will cause error in Colab

from ultralytics import YOLO
import cv2
from IPython.display import display, Image, clear_output
import io
import time # For controlling frame rate

model = YOLO('yolov8n.pt')

# NOTE: cv2.VideoCapture(0) will not work in Colab for your local webcam.
# If you want to process a video, you need to upload a video file and use its path.
# For demonstration, we'll simulate a video stream or require a valid video path.
# For now, let's assume `cap` might fail, as it did in previous cells.
cap = cv2.VideoCapture(0)

print("Starting object detection. Displaying frames in Colab output.")
print("To stop, interrupt the kernel.")

max_frames_to_process = 100 # Limiting frames for demonstration
frame_count = 0

try:
    while frame_count < max_frames_to_process:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame or camera not accessible. Exiting.")
            break

        results = model(frame)

        threat_detected = False
        annotated_frame = frame.copy() # Make a copy to draw on

        for r in results:
            for box in r.boxes:
                class_id = int(box.cls[0])
                object_name = model.names[class_id]

                if object_name == 'knife': # Check for 'knife' or any other threat
                    threat_detected = True

                # Draw bounding boxes (optional, for visual feedback)
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                cv2.rectangle(annotated_frame, (x1, y1), (x2, y2), (255, 0, 0), 2) # Blue box for detected objects
                cv2.putText(annotated_frame, object_name, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2)

        if threat_detected:
            cv2.putText(annotated_frame, "WEAPON DETECTED!", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
            cv2.rectangle(annotated_frame, (0, 0), (annotated_frame.shape[1], annotated_frame.shape[0]), (0, 0, 255), 5)
            # In Colab, winsound.Beep() will not work. Consider alternative for alert.
            # print("ALERT: WEAPON DETECTED!") # Or play a sound via JavaScript if more advanced UI is used

        # Display the annotated frame in Colab output
        is_success, buffer = cv2.imencode(".jpg", annotated_frame)
        if is_success:
            i = Image(data=buffer.tobytes())
            clear_output(wait=True) # Clear previous frame for updated display
            display(i)

        time.sleep(0.1) # Small delay to control refresh rate
        frame_count += 1

except KeyboardInterrupt:
    print("Process interrupted by user.")

finally:
    cap.release()
    print("Camera released and cleanup complete.")
    # cv2.destroyAllWindows() is not needed in Colab and would cause an error.

from ultralytics import YOLO
import cv2
from IPython.display import display, Image, clear_output # Added for Colab display
import io
import time # Added for controlling frame rate

# winsound is Windows-specific and will not work in Colab (Linux environment)
# import winsound  # REMOVED

model = YOLO('yolov8n.pt')

# NOTE: cv2.VideoCapture(0) will likely not work in Colab for your local webcam.
# For demonstration, you might need to upload a video file and use its path,
# or integrate with specific Colab webcam utilities.
cap = cv2.VideoCapture(0)

print("Starting object detection. Displaying frames in Colab output.")
print("To stop, interrupt the kernel or wait for max_frames_to_process.")

max_frames_to_process = 100 # Limiting frames for demonstration in Colab
frame_count = 0

try:
    while frame_count < max_frames_to_process: # Loop controlled by frame_count instead of cv2.waitKey
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame or camera not accessible. Exiting.")
            break

        results = model(frame)
        threat_detected = False
        annotated_frame = frame.copy() # Use a copy to draw on

        for r in results:
            for box in r.boxes:
                class_id = int(box.cls[0])
                object_name = model.names[class_id]

                if object_name == 'knife': # Check for 'knife'
                    threat_detected = True

                # Draw bounding boxes (optional, for visual feedback)
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                cv2.rectangle(annotated_frame, (x1, y1), (x2, y2), (255, 0, 0), 2)
                cv2.putText(annotated_frame, object_name, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2)


        if threat_detected:
            cv2.rectangle(annotated_frame, (0, 0), (annotated_frame.shape[1], annotated_frame.shape[0]), (0, 0, 255), 10)
            cv2.putText(annotated_frame, "WEAPON DETECTED!", (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 0, 255), 4)

            print("ALERT: WEAPON DETECTED!") # Replaced winsound.Beep with a print statement

        # Display the annotated frame in Colab output using IPython.display
        is_success, buffer = cv2.imencode(".jpg", annotated_frame)
        if is_success:
            i = Image(data=buffer.tobytes())
            clear_output(wait=True) # Clear previous frame for updated display
            display(i)

        time.sleep(0.1) # Small delay to control refresh rate
        frame_count += 1

except KeyboardInterrupt:
    print("Process interrupted by user.")

finally:
    cap.release()
    print("Camera released and cleanup complete.")
    # cv2.destroyAllWindows() is not needed and would cause an error in Colab
    # cv2.imshow and cv2.waitKey are also not compatible with Colab's headless environment.

# import winsound # winsound is Windows-specific and will not work in Colab (Linux environment)
print("Testing Sound...")

# winsound.Beep(1000, 1000) # This function will not work in Colab
print("Sound cannot be played directly in Colab kernel.")
print("If an alert is needed, use print statements or a JavaScript solution.")

